version: "3.7"
services: 
    app:
        build: 
            context: ./
            args: 
                - CENTOS_VERSION=${CENTOS_VERSION}
                - BAOTA_INSTALL_PATH=${BAOTA_INSTALL_PATH}
        stdin_open: true
        tty: true
        privileged: true
        ports: 
            - ${BAOTA_PORT}:8888
            - ${WEB_PORT}:80
            - ${HTTPS_PORT}:443
            - ${FTP_DATA_PORT}:20
            - ${FTP_PORT}:21
            - ${SSH_PORT}:22
            - ${MYSQL_PORT}:3306
            - ${PHPMYADMIN_PORT}:888
        volumes: 
            - ${WEB_PATH}:/www/wwwroot
            - ${BACKUP_PATH}:/www/backup
            - ${LOGS_PATH}:/www/wwwlogs
            - ${DOCKERSCRIPT_PATH}:/www/DockerScript

networks: 
    default:
        driver: ${NETWORKS_DRIVER}