version: "3"
services: 
    app:
        build: 
            context: ./app/
            args: 
                - CENTOS_VERSION=${CENTOS_VERSION}
                - BAOTA_INSTALL_PATH=${BAOTA_INSTALL_PATH}
        stdin_open: true
        tty: true
        privileged: true
        ports: 
            - ${BAOTA_PORT}:8888
            - ${WEB_PORT}:80
            - ${HTTPS_PORT}:443
            - ${FTP_DATA_PORT}:20
            - ${FTP_PORT}:21
            - ${SSH_PORT}:22
            - ${MYSQL_PORT}:3306
            - ${PHPMYADMIN_PORT}:888
        volumes: 
            - www:/www
            - usr:/usr
            - etc:/etc
            - ${WEB_PATH}:/www/wwwroot
            - ${BACKUP_PATH}:/www/backup
            - ${LOGS_PATH}:/www/wwwlogs
volumes: 
    www:
        driver: ${VOLUMES_DRIVER}
    usr:
        driver: ${VOLUMES_DRIVER}
    etc:
        driver: ${VOLUMES_DRIVER}

networks: 
    default:
        driver: ${NETWORKS_DRIVER}